### ISSUE TITLE
 Are other versions of react-navigation compatible?

### ISSUE THREAD

**Issue by chars1205** [GeekyAnts/vue-native-router#10]
I have a question and I am now dependencies on react-navgation v1.5.11 on the vue-native-router. Is the upper version of react-navigation unusable? If so, how should I use it?

**Comment by envisean** [comment]
I'd also like to see if we could get this upgraded to the latest version of React Navigation

**Comment by tmaly1980** [comment]
Just taking a quick glance into src/index.js, it looks to take into consideration newer versions of react-navigation. Try upgrading the dependency and see what happens?

**Comment by tmaly1980** [comment]
I've forked a version to be compatible, not much other than changing the dependency:

https://github.com/tmaly1980/vue-native-router/

This is my App.vue:

```
<template>
  <app-navigation></app-navigation>
</template>
 
<style>
.container {
  background-color: white;
  align-items: center;
  justify-content: center;
  flex: 1;
}
.text-color-primary {
  color: blue;
}
</style>
<script>
import Vue from "vue-native-core";
import { VueNativeBase } from "native-base";

// registering all native-base components to the global scope of the Vue
Vue.use(VueNativeBase);

import MeetingsScreen from "./src/screens/Meetings"
import FilesScreen from "./src/screens/Files"

import { createBottomTabNavigator, createNavigationContainer } from "vue-native-router";

const AppNavigation = createBottomTabNavigator(
  {
    Meetings: {
      screen: MeetingsScreen,
    },
    Files: {
      screen: FilesScreen,
    }
  },
  {
    // Options
  }
);

export default {
  components: { AppNavigation: createNavigationContainer(AppNavigation) }
}
</script>
```

**Comment by RishabhKarnad** [comment]
As of the latest release, we use `react-navigation` v3. We'll probably upgrade every time there is a  newer version.
