### ISSUE TITLE
dependency woes

### ISSUE THREAD

**Issue by knot22** [GeekyAnts/vue-native-router#24]
After running this command:
![image](https://user-images.githubusercontent.com/20587751/71025263-48803380-20cc-11ea-8d7d-c1ce60ab2378.png)
and getting this output:
![image](https://user-images.githubusercontent.com/20587751/71025294-5cc43080-20cc-11ea-90ab-e42011099be1.png)

I checked to see what packages were globally installed in my environment:
![image](https://user-images.githubusercontent.com/20587751/71025331-6f3e6a00-20cc-11ea-996b-7e06a6c36051.png)

The docs do not mention these as dependencies for Vue Native Router.  Should they be listed in the docs as dependencies?  If I install these, will that lead to more unmet peer dependencies?

Futhermore, after installing the 3 react dependencies that the docs did list for Vue Native Router (react-native-reanimated, react-native-gesture-handler, react-native-paper), the globally installed packages then looked like this:
![image](https://user-images.githubusercontent.com/20587751/71025622-05729000-20cd-11ea-9ac9-039e5d147d9c.png)

It seems there are more react dependencies now.  Why aren't those listed in the Vue Native Router docs?  If I install these, will that lead to more unmet peer dependencies?

**Comment by RishabhKarnad** [comment]
Hey @knot22. All the dependencies listed in the docs (apart from `vue-native-cli`, `expo-cli` and `react-native-cli`) are meant to be installed locally in the project.

Use 
```sh
$ npm i --save <packageName>
```

It may work if you install it globally, but I wouldn't recommend it.
