### ISSUE TITLE
How to add header titles to Screens

### ISSUE THREAD

**Issue by OElesin** [GeekyAnts/vue-native-router#25]
I am currently unable to add headers to screens. As described in the react-navigation example, nothing similar is available in Vue-native implementation.

When creating the stackNavigator, I am able to specify a general header title for all screens but not dynamic per screen. See below:
```js
const StackNavigator = createStackNavigator(
  {
    Drawer: DrawerNavigator,
    Home: HomeScreen,
    Details: UrlPreviewScreen
  },
  {
    initialRouteName: "Home",
    defaultNavigationOptions: {
      title: 'Home',
      headerStyle: {
        backgroundColor: "#f4511e"
      },
      headerTintColor: "#fff",
      headerTitleStyle: {
        fontWeight: "bold"
      }
    }
  }
);
```

Kindly help on how to specify per screen. Thanks in advance

**Comment by nashsaint** [comment]
Am having same issue, did anyone find a solution to this?

**Comment by dara7** [comment]
me the same

**Comment by dara7** [comment]
i don't know how to add title header but i just remove the header bar by **headerMode: "none"** and 
customize it by my self in each page
``
const StackNavigator = createStackNavigator(
  {
    Drawer: DrawerNavigator,
  },
  {
    headerMode: "none"
  }
);
``

**Comment by waritthornnudee** [comment]
![image](https://user-images.githubusercontent.com/26889841/82808037-4ad48e00-9eb3-11ea-8397-99c013b28eae.png)
If i understand you right :)

**Comment by RishabhKarnad** [comment]
Yes, @waritthornnudee's solution should work.

https://reactnavigation.org/docs/4.x/stack-navigator#navigationoptions-for-screens-inside-of-the-navigator

**Comment by UsamaAltaf** [comment]
I am using as this 

```
const DrawerNavigator = createDrawerNavigator(
  {
    Login: LoginScreen,
    TenantDetails: TenantScreen,
    TenantInvoices: InvoiceScreen,
    CustomList: CustomListScreen,
  },
  {
    initialRouteName: 'Login',
  },
);

const StackNavigator = createStackNavigator({
  Login: {
    screen: LoginScreen,
    navigationOptions: {
      headerTitle: 'Login',
    },
  },
  TenantDetails: {
    screen: TenantScreen,
    navigationOptions: {
      headerTitle: 'Tenant Details',
    },
  },
  TenantInvoices: {
    screen: InvoiceScreen,
    navigationOptions: {
      headerTitle: 'Tenant Invoices',
    },
  },
  CustomList: {
    screen: CustomListScreen,
    navigationOptions: {
      headerTitle: 'Custom List',
    },
  },
  Drawer: DrawerNavigator, //use this below if we use this abve the screens name title will not be shown I know I am late but this will help new comers
});
```

**Comment by kamyasimon** [comment]
> I am currently unable to add headers to screens. As described in the react-navigation example, nothing similar is available in Vue-native implementation.
> 
> When creating the stackNavigator, I am able to specify a general header title for all screens but not dynamic per screen. See below:
> 
> ```js
> const StackNavigator = createStackNavigator(
>   {
>     Drawer: DrawerNavigator,
>     Home: HomeScreen,
>     Details: UrlPreviewScreen
>   },
>   {
>     initialRouteName: "Home",
>     defaultNavigationOptions: {
>       title: 'Home',
>       headerStyle: {
>         backgroundColor: "#f4511e"
>       },
>       headerTintColor: "#fff",
>       headerTitleStyle: {
>         fontWeight: "bold"
>       }
>     }
>   }
> );
> ```
> 
> Kindly help on how to specify per screen. Thanks in advance

THANK YOU FOR THE TITLE SOUTION, I will test it soon. But Brilliant idea shared. Thanks

**Comment by UsamaAltaf** [comment]
> 
> 
> > I am currently unable to add headers to screens. As described in the react-navigation example, nothing similar is available in Vue-native implementation.
> > When creating the stackNavigator, I am able to specify a general header title for all screens but not dynamic per screen. See below:
> > ```js
> > const StackNavigator = createStackNavigator(
> >   {
> >     Drawer: DrawerNavigator,
> >     Home: HomeScreen,
> >     Details: UrlPreviewScreen
> >   },
> >   {
> >     initialRouteName: "Home",
> >     defaultNavigationOptions: {
> >       title: 'Home',
> >       headerStyle: {
> >         backgroundColor: "#f4511e"
> >       },
> >       headerTintColor: "#fff",
> >       headerTitleStyle: {
> >         fontWeight: "bold"
> >       }
> >     }
> >   }
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Kindly help on how to specify per screen. Thanks in advance
> 
> THANK YOU FOR THE TITLE SOUTION, I will test it soon. But Brilliant idea shared. Thanks

Have you find any soution yet?
