### ISSUE TITLE
cannot start app

### ISSUE THREAD

**Issue by knot22** [GeekyAnts/vue-native-router#26]
I was able to clone this project and run `npm install` successfully; however, when the `expo start` command is given the app does not start and this error appears:

> Cannot determine which native SDK version your project uses because the module 'expo' is not installed.  Please install it with 'yarn add expo' and try again.

expo-cli is installed globally in the environment where I'm trying to run this project as can be seen here:
![image](https://user-images.githubusercontent.com/20587751/71773849-0bb89700-2f2a-11ea-9c40-67418950407f.png)

This environment runs other Vue Native projects without issue.  For instance, the KitchenSink app runs fine so I'm unsure as to why this project won't run.  Do you have any ideas?

**Comment by knot22** [comment]
I ended up recreating these examples manually rather than try to use the cloned version.

**Comment by KaumadieKariyawasam** [comment]
Try npm install expo instead of yard add expo.

If you have npm installed already then you can replace yarn add with npm install always.
like as -: npm install yarn add
