### ISSUE TITLE
react-native-gesture-handler > 1.4.0 breaks tab navigations.

### ISSUE THREAD

**Issue by Mgrmjp** [GeekyAnts/vue-native-router#29]
Expo is suggesting to install react-native-gesture-handler from ~1.5.0 version range.

If you do that MaterialTopTabNavigation and probably bottom ones as well will not work and Expo will crash without errors. Would be useful to specify this in the vue-native docs where you instruct to:

>npm install -g react-native-gesture-handler

**Comment by WhidRubeld** [comment]
+1

**Comment by RishabhKarnad** [comment]
Sorry that this reply took so long.

Yeah, it would be better to specify the supported versions of the peerDeps in the docs. Will update this.

Could you provide the error message?

**Comment by Mgrmjp** [comment]
No clue about this since it's been so long. Sorry.

**Comment by RishabhKarnad** [comment]
I'll close this issue then. This can be reopened if anyone faces similar issues with `vue-native-router@~0.2.0`
