### ISSUE TITLE
Disabling back swipe

### ISSUE THREAD

**Issue by maxencedouet** [GeekyAnts/vue-native-router#30]
Hello, 

We would like to disable back swipe on main pages but we don't manage to implement it on vue-native-router (we are using createBottomTabNavigator) ... 

react-native-router props: https://reactnavigation.org/docs/material-top-tab-navigator/#swipeenabled

thank you very much for your help.

**Comment by RishabhKarnad** [comment]
Sorry that this reply took so long. From the docs, it doesn't seem as though there is such a prop for bottom tabs.

https://reactnavigation.org/docs/4.x/bottom-tab-navigator/
