### ISSUE TITLE
#feature Add react-navigation v5, component based router

### ISSUE THREAD

**Issue by krunaldodiya** [GeekyAnts/vue-native-router#31]
currently i am using react-native, but just starting liking vue-native as well, but reading the docs found out, it has no react-navigation v5 support yet, 

any plan for future implementation ?

**Comment by RishabhKarnad** [comment]
No plans as of now. We are actually upgrading to react-navigation v4 so that users can stay with maintained code, while avoiding breaking changes.

**Comment by Corymillz** [comment]
Any update on this yet? Want to use some of the features in v5 but can't
