### ISSUE TITLE
Add a callback when a screen is focused

### ISSUE THREAD

**Issue by Narduzzi** [GeekyAnts/vue-native-router#32]
Hello,

I would like to add a callback when a screen is focused.
I have tried to add the following line in the mounted hook :
`this.navigation.addListener('focus',()=>{...})`

But it doesn't work. The error is the following : "focus is not a valid event". 

Can you help me?

**Comment by kelsohmm** [comment]
I have the same problem +1

**Comment by Zombarian** [comment]
Same issue here +1

**Comment by Zombarian** [comment]
I found one way of doing it: using https://reactnavigation.org/docs/4.x/navigation-events/. It has to be added to every screen

**Comment by RishabhKarnad** [comment]
This should no longer be an issue after the upcoming release (we are upgrading to react-navigation v4)

**Comment by iemarjay** [comment]
> I found one way of doing it: using https://reactnavigation.org/docs/4.x/navigation-events/. It has to be added to every screen

Can you share how you solve this because... it did not work when I tried it
