### ISSUE TITLE
console.error:"navigation.emit only supports the 'refocus' event currently."

### ISSUE THREAD

**Issue by TolrenFrank** [GeekyAnts/vue-native-router#33]
console.error: "navigation.emit only supports the 'refocus' event currently."
error
    
emit
    D:\work\vue-native\test\node_modules\vue-native-router\node_modules\@react-navigation\native\src\index.js:24:21
onEvent
    D:\work\vue-native\test\node_modules\react-navigation-drawer\lib\module\views\DrawerView.js:127:56
<unknown>
    D:\work\vue-native\test\node_modules\react-navigation\src\index.js:6
<unknown>
    
<unknown>
    D:\work\vue-native\test\node_modules\vue-native-router\node_modules\@react-navigation\core\lib\module\index.js:1:712
forEach
    [native code]
emit
    
<unknown>
    D:\work\vue-native\test\node_modules\vue-native-router\node_modules\@react-navigation\core\lib\module\index.js:1:1409
<unknown>
    D:\work\vue-native\test\node_modules\query-string\index.js:180:23
forEach
    [native code]
dispatchActions
    
componentDidMount$
    
tryCatch
    
invoke
    D:\work\vue-native\test\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:2803:16
tryCatch
    
invoke
    D:\work\vue-native\test\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:2617:4
<unknown>
    
tryCallOne
    D:\work\vue-native\test\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:4415:2
<unknown>
    D:\work\vue-native\test\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:4544:2
_callTimer
    D:\work\vue-native\test\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:9375:9
_callImmediatesPass
    
callImmediates
    D:\work\vue-native\test\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:9750:7
callImmediates
    [native code]
__callImmediates
    
<unknown>
    
__guard
    D:\work\vue-native\test\node_modules\react-native\Libraries\ART\ReactNativeART.js:388:9
flushedQueue
    
flushedQueue
    [native code]
invokeCallbackAndReturnFlushedQueue
    [native code]

**Comment by n0bit** [comment]
I have the same issue

**Comment by RishabhKarnad** [comment]
This is an issue with react-navigation 3. If you see the red screen of death every time due to this `console.error`, you can use this solution to only log it instead:

https://stackoverflow.com/a/46400182

**Comment by jonnycraze** [comment]
This is causing quite a bit of frustration on my end. Your suggested workaround does allow me to see the screen, but my terminal is being continually flooded with this error making it impossible to debug anything else.

Is there an anticipated fix for this problem?

**Comment by RishabhKarnad** [comment]
This will be fixed in the upcoming release
