### ISSUE TITLE
Why react-native-screens needed ?

### ISSUE THREAD

**Issue by ludonvl** [GeekyAnts/vue-native-router#35]
I'm just trying to use vue-native-router on a fresh vue-native project using react-native cli (not expo).
After installing package needed like gesture-handler, paper, and reanimated the stackNavigator breaks and shows that Module : `react-native-screens` does not exist. 

<img width="331" alt="Capture d’écran 2020-08-02 à 23 39 44" src="https://user-images.githubusercontent.com/14062380/89133316-26340c80-d51b-11ea-9426-821fb4ef65cb.png">

What can I do ?

Thanks for some help

My package.json 
`{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-paper": "^2.16.0",
    "react-native-reanimated": "~1.2.0",
    "vue-native-core": "0.1.4",
    "vue-native-helper": "0.1.4",
    "vue-native-router": "~0.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/runtime": "^7.11.0",
    "babel-jest": "^26.2.2",
    "jest": "^26.2.2",
    "metro-react-native-babel-preset": "^0.61.0",
    "react-test-renderer": "16.8.3",
    "vue-native-scripts": "0.1.4"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by elahekaramzade** [comment]
same issue with using expo cli .

**Comment by RishabhKarnad** [comment]
react-native-screens is a required peerDependency of one of the modules in react-navigation. We'll make an effort to document the supported versions and peer dependencies in a better way going forward. It seems one of the dependencies added this as in a minor version update
