### ISSUE TITLE
vue-native-router error

### ISSUE THREAD

**Issue by ukik** [GeekyAnts/vue-native-router#39]
error: bundling failed: Error: Unable to resolve module `vue-native-router` from `E:\- VUE NATIVE\demo\App.vue`: Module `vue-native-router` does not exist in the Haste module map or in these directories:

**Comment by ukik** [comment]
Window, i use Android device Realme. Code what I use is copy paste from official vue-native site.

**Comment by ukik** [comment]
Terminal 1
λ react-native run-android
info JS server already running.
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

> Task :app:installDebug
08:49:51 V/ddms: execute: running am get-config
08:49:51 V/ddms: execute 'am get-config' on 'JF9D9H6TPJ7HKZAM' : EOF hit. Read: -1
08:49:51 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'RMX1941 - 9' for app:debug
08:49:51 D/app-debug.apk: Uploading app-debug.apk onto device 'JF9D9H6TPJ7HKZAM'
08:49:51 D/Device: Uploading file onto device 'JF9D9H6TPJ7HKZAM'
08:49:51 D/ddms: Reading file permision of E:\- VUE NATIVE\demo\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
08:49:53 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
08:49:58 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'JF9D9H6TPJ7HKZAM' : EOF hit. Read: -1
08:49:58 V/ddms: execute: returning
08:49:58 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
08:49:58 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'JF9D9H6TPJ7HKZAM' : EOF hit. Read: -1
08:49:58 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 16s
26 actionable tasks: 1 executed, 25 up-to-date
info Running C:\Android\android-sdk/platform-tools/adb -s JF9D9H6TPJ7HKZAM reverse tcp:8081 tcp:8081
info Starting the app on JF9D9H6TPJ7HKZAM (C:\Android\android-sdk/platform-tools/adb -s JF9D9H6TPJ7HKZAM shell am start -n com.demo/com.demo.MainActivity)...
Starting: Intent { cmp=com.demo/.MainActivity }


Terminal 2
Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `react-native-paper` from `E:\- VUE NATIVE\demo\node_modules\react-navigation-material-bottom-tabs\src\views\MaterialBottomTabView.tsx`: Module `react-native-paper` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (E:\- VUE NATIVE\demo\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (E:\- VUE NATIVE\demo\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (E:\- VUE NATIVE\demo\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
    at Object.resolve (E:\- VUE NATIVE\demo\node_modules\metro\src\lib\transformHelpers.js:261:42)
    at dependencies.map.result (E:\- VUE NATIVE\demo\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (E:\- VUE NATIVE\demo\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:18)
    at E:\- VUE NATIVE\demo\node_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\- VUE NATIVE\demo\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
 DELTA  [android, dev] ..\..\../index.js ▓▓▓▓▓▓▓▓▓░░░░░░░ 61.4% (562/717), failed.

::ffff:127.0.0.1 - - [12/Nov/2020:12:50:21 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"

**Comment by kamyasimon** [comment]
> error: bundling failed: Error: Unable to resolve module `vue-native-router` from `E:\- VUE NATIVE\demo\App.vue`: Module `vue-native-router` does not exist in the Haste module map or in these directories:

Instead of Vue-Router, Use-> import {...} from 'react-navigation'..
on Drawer, StackNavigator,Tabs...use-> import {......} from 'react-navigation-drawer || stack || tabs....
hope i have simplified and made it clear for you.
The reason for the new modifications is because react-native upgraded the navigation.
You can visit my youtube channel for more demonstartions

**Comment by RishabhKarnad** [comment]
Please reopen the issue in case the steps suggested in the error do not work

> To resolve try the following:
> 
> 1. Clear watchman watches: watchman watch-del-all.
> 2. Delete the node_modules folder: rm -rf node_modules && npm install.
> 3. Reset Metro Bundler cache: rm -rf /tmp/metro-bundler-cache-* or npm start -- --reset-cache.
> 4. Remove haste cache: rm -rf /tmp/haste-map-react-native-packager-*.
