### ISSUE TITLE
multiple peer deps missing

### ISSUE THREAD

**Issue by joshuagamboa** [GeekyAnts/vue-native-router#4]
I get several warnings after trying to add this.

npm ERR! peer dep missing: vue-native-core@0.0.5, required by vue-native-router@0.0.1-alpha.3
npm ERR! peer dep missing: vue-native-helper@0.0.6, required by vue-native-router@0.0.1-alpha.3
npm ERR! peer dep missing: vue-native-scripts@0.0.7, required by vue-native-router@0.0.1-alpha.3
npm ERR! peer dep missing: react-native@^0.51 || ^0.52 || ^0.53 || ^0.54, required by react-native-maps@0.21.0
npm ERR! peer dep missing: react-native-web@*, required by react-native-web-maps@0.1.0
npm ERR! peer dep missing: react@15.5.4, required by react-google-maps@7.3.0
npm ERR! peer dep missing: react-dom@15.5.4, required by react-google-maps@7.3.0
npm ERR! peer dep missing: react@^0.14.6 || ^15.0.0-0, required by react-prop-types-element-of-type@2.2.0
npm ERR! peer dep missing: eslint@^3.17.0 || ^4.0.0, required by eslint-plugin-react-native@3.2.1

**Comment by RishabhKarnad** [comment]
Please reopen if you still face this issue with the latest version.
