### ISSUE TITLE
Version ~0.2.0 npm compatability [MAR 2021]

### ISSUE THREAD

**Issue by ido-aim** [GeekyAnts/vue-native-router#45]
I see that `vue-native-router":"~0.2.0”` still requires old packages like

- `“vue-native-core": "~0.1.0”`,
- `"vue-native-helper": "~0.1.0”`,
- `"react-native@":"^0.59.0"`

When install with `npm i`, here are some parts of error

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project@0.2.0
npm ERR! Found: vue-native-core@0.2.0
npm ERR! node_modules/vue-native-core
npm ERR!   vue-native-core@"~0.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue-native-core@"~0.1.0" from vue-native-router@0.2.0
npm ERR! node_modules/vue-native-router
npm ERR!   vue-native-router@"~0.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/AT/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/AT/.npm/_logs/2021-03-28T08_31_00_269Z-debug.log
```
I believe `npm` wasn’t update but please verify if there were some issues left

Thanks in advance

**Comment by ido-aim** [comment]
my package.json is using these
{
    "react": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/refs/tags/sdk-41.0.0.tar.gz",
    "react-native-easy-grid": "^0.2.2",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-paper": "^2.16.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-screens": "~2.15.2",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "vue-native-core": "~0.2.0",
    "vue-native-helper": "~0.2.0",
    "vue-native-router":"~0.2.0",
}

**Comment by RishabhKarnad** [comment]
This should be fixed now
