### ISSUE TITLE
Expo console warnings about react-navigation library

### ISSUE THREAD

**Issue by vcavallo** [GeekyAnts/vue-native-router#49]
I'm getting streams of this in the Expo console:

```
It appears that you are using old version of react-navigation library. Please update @react-navigation/bottom-tabs, @react-navigation/stack and @react-navigation/drawer to version 5.10.0 or above to take full advantage of new functionality added to react-native-screens
```

package.json dependencies:

```
  "dependencies": {
    "axios": "^0.21.1",
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-paper": "^4.7.2",
    "react-native-reanimated": "^2.1.0",
    "react-native-screens": "^3.0.0",
    "react-native-web": "~0.13.12",
    "vue-native-core": "0.2.0",
    "vue-native-helper": "0.2.0",
    "vue-native-router": "^0.2.1",
    "vuex": "^3.6.2"
  },
```

the relevant parts of yarn.lock:

```
vue-native-core@0.2.0:
  version "0.2.0"
  resolved "https://registry.yarnpkg.com/vue-native-core/-/vue-native-core-0.2.0.tgz#990dc432b90e289489e4415a6ad0042b1aa3101f"
  integrity sha512-eJpj0oIwSC2QYH1WJscW0ZusgAtaw5wNx/mDsdFdv8nDYsls88TeZAiTmn9PVK0Lj6X5MKNa30R3LI7DRTTv+w==


vue-native-router@^0.2.1:
  version "0.2.1"
  resolved "https://registry.yarnpkg.com/vue-native-router/-/vue-native-router-0.2.1.tgz#d0fde7c537a90049819bf2551e67a70e9724ef43"
  integrity sha512-Quy022MZxGk3NcX6RfLOSlTQiQ7mpQMGCKeCnJq8pQuJXtDbshoHDf9UQ9Bjnev2nbQSltXUeSyj6Saw22b94g==
  dependencies:
    lodash.get "^4.4.2"
    react-navigation "^4.1.1"
    react-navigation-drawer "^2.3.4"
    react-navigation-material-bottom-tabs "^2.3.0"
    react-navigation-stack "^1.7.3"
    react-navigation-tabs "^2.7.0"

"@react-navigation/core@^3.7.9":
  version "3.7.9"
  resolved "https://registry.yarnpkg.com/@react-navigation/core/-/core-3.7.9.tgz#3f7ba0fcb6c8d74a77a057382af198d84c7c4e3b"
  integrity sha512-EknbzM8OI9A5alRxXtQRV5Awle68B+z1QAxNty5DxmlS3BNfmduWNGnim159ROyqxkuDffK9L/U/Tbd45mx+Jg==
  dependencies:
    hoist-non-react-statics "^3.3.2"
    path-to-regexp "^1.8.0"
    query-string "^6.13.6"
    react-is "^16.13.0"

"@react-navigation/native@^3.8.4":
  version "3.8.4"
  resolved "https://registry.yarnpkg.com/@react-navigation/native/-/native-3.8.4.tgz#4d77f86506364ecf18b33c7f8740afb6763d0b37"
  integrity sha512-gXSVcL7bfFDyVkvyg1FiAqTCIgZub5K1X/TZqURBs2CPqDpfX1OsCtB9D33eTF14SpbfgHW866btqrrxoCACfg==
  dependencies:
    hoist-non-react-statics "^3.3.2"
    react-native-safe-area-view "^0.14.9"

react-navigation-drawer@^2.3.4:
  version "2.7.0"
  resolved "https://registry.yarnpkg.com/react-navigation-drawer/-/react-navigation-drawer-2.7.0.tgz#794b4214a6b5debde1f8f90e18e3e63aa738e628"
  integrity sha512-BKQSTpFPGVI3caFlIbY921NYTRDAf9XFCCmyy4aDlxZLI5FNh8FqzrG10voc5AGy7RegjLdNkkJa40ugu0I5jA==

react-navigation-material-bottom-tabs@^2.3.0:
  version "2.3.4"
  resolved "https://registry.yarnpkg.com/react-navigation-material-bottom-tabs/-/react-navigation-material-bottom-tabs-2.3.4.tgz#fddcd1c3de9355e6c527a612b23dfb4319f6380b"
  integrity sha512-NHHFsDg8AJupfPJ2ybIjCzT8VifBFd0LXxAO+RBermtHF2wrHVyFIcpTnYDr1WHgwwRAOrKKg1Hd2TG7TjX6Bg==

react-navigation-stack@^1.7.3:
  version "1.10.3"
  resolved "https://registry.yarnpkg.com/react-navigation-stack/-/react-navigation-stack-1.10.3.tgz#e714e442b20427f0d2d3c18fce1f9e8cfe69be0b"
  integrity sha512-1gksFi/g/Lg9sBhgLlD0OiEB5xnatHb4C0eNMA5tli9cTVlhq375XNPIqOiTyftibBmjdApAsZFj5srUCoOu/w==
  dependencies:
    prop-types "^15.7.2"

react-navigation-tabs@^2.7.0:
  version "2.11.0"
  resolved "https://registry.yarnpkg.com/react-navigation-tabs/-/react-navigation-tabs-2.11.0.tgz#fbea5c8154b6b1b86e1117a1184b98069c5b8bfa"
  integrity sha512-mrnHfTVKVvoy5AWJY3vLt6cQLZQlVLgGUykTZerFBdTmxC/rFdsv+y2ec+rmSNy7u5nX+hlQBFvm/MIJ7w01wQ==
  dependencies:
    hoist-non-react-statics "^3.3.2"
    react-lifecycles-compat "^3.0.4"
    react-native-iphone-x-helper "^1.3.0"
    react-native-tab-view "^2.15.2"

react-navigation@^4.1.1:
  version "4.4.4"
  resolved "https://registry.yarnpkg.com/react-navigation/-/react-navigation-4.4.4.tgz#8cda2219196311db440e54998bc724523359949f"
  integrity sha512-08Nzy1aKEd73496CsuzN49vLFmxPKYF5WpKGgGvkQ10clB79IRM2BtAfVl6NgPKuUM8FXq1wCsrjo/c5ftl5og==
  dependencies:
    "@react-navigation/core" "^3.7.9"
    "@react-navigation/native" "^3.8.4"

```

I'm on Ubuntu 18.04. 
Let me know what other information I can provide to help.

**Comment by RishabhKarnad** [comment]
vue-native-router uses react-navigation 4. If you wish to use react-navigation 5 you can install and use it directly

**Comment by kamyasimon** [comment]
> I'm getting streams of this in the Expo console:
> 
> ```
> It appears that you are using old version of react-navigation library. Please update @react-navigation/bottom-tabs, @react-navigation/stack and @react-navigation/drawer to version 5.10.0 or above to take full advantage of new functionality added to react-native-screens
> ```
> 
> package.json dependencies:
> 
> ```
>   "dependencies": {
>     "axios": "^0.21.1",
>     "expo": "~40.0.0",
>     "expo-status-bar": "~1.0.3",
>     "react": "16.13.1",
>     "react-dom": "16.13.1",
>     "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
>     "react-native-gesture-handler": "^1.10.3",
>     "react-native-paper": "^4.7.2",
>     "react-native-reanimated": "^2.1.0",
>     "react-native-screens": "^3.0.0",
>     "react-native-web": "~0.13.12",
>     "vue-native-core": "0.2.0",
>     "vue-native-helper": "0.2.0",
>     "vue-native-router": "^0.2.1",
>     "vuex": "^3.6.2"
>   },
> ```
> 
> the relevant parts of yarn.lock:
> 
> ```
> vue-native-core@0.2.0:
>   version "0.2.0"
>   resolved "https://registry.yarnpkg.com/vue-native-core/-/vue-native-core-0.2.0.tgz#990dc432b90e289489e4415a6ad0042b1aa3101f"
>   integrity sha512-eJpj0oIwSC2QYH1WJscW0ZusgAtaw5wNx/mDsdFdv8nDYsls88TeZAiTmn9PVK0Lj6X5MKNa30R3LI7DRTTv+w==
> 
> 
> vue-native-router@^0.2.1:
>   version "0.2.1"
>   resolved "https://registry.yarnpkg.com/vue-native-router/-/vue-native-router-0.2.1.tgz#d0fde7c537a90049819bf2551e67a70e9724ef43"
>   integrity sha512-Quy022MZxGk3NcX6RfLOSlTQiQ7mpQMGCKeCnJq8pQuJXtDbshoHDf9UQ9Bjnev2nbQSltXUeSyj6Saw22b94g==
>   dependencies:
>     lodash.get "^4.4.2"
>     react-navigation "^4.1.1"
>     react-navigation-drawer "^2.3.4"
>     react-navigation-material-bottom-tabs "^2.3.0"
>     react-navigation-stack "^1.7.3"
>     react-navigation-tabs "^2.7.0"
> 
> "@react-navigation/core@^3.7.9":
>   version "3.7.9"
>   resolved "https://registry.yarnpkg.com/@react-navigation/core/-/core-3.7.9.tgz#3f7ba0fcb6c8d74a77a057382af198d84c7c4e3b"
>   integrity sha512-EknbzM8OI9A5alRxXtQRV5Awle68B+z1QAxNty5DxmlS3BNfmduWNGnim159ROyqxkuDffK9L/U/Tbd45mx+Jg==
>   dependencies:
>     hoist-non-react-statics "^3.3.2"
>     path-to-regexp "^1.8.0"
>     query-string "^6.13.6"
>     react-is "^16.13.0"
> 
> "@react-navigation/native@^3.8.4":
>   version "3.8.4"
>   resolved "https://registry.yarnpkg.com/@react-navigation/native/-/native-3.8.4.tgz#4d77f86506364ecf18b33c7f8740afb6763d0b37"
>   integrity sha512-gXSVcL7bfFDyVkvyg1FiAqTCIgZub5K1X/TZqURBs2CPqDpfX1OsCtB9D33eTF14SpbfgHW866btqrrxoCACfg==
>   dependencies:
>     hoist-non-react-statics "^3.3.2"
>     react-native-safe-area-view "^0.14.9"
> 
> react-navigation-drawer@^2.3.4:
>   version "2.7.0"
>   resolved "https://registry.yarnpkg.com/react-navigation-drawer/-/react-navigation-drawer-2.7.0.tgz#794b4214a6b5debde1f8f90e18e3e63aa738e628"
>   integrity sha512-BKQSTpFPGVI3caFlIbY921NYTRDAf9XFCCmyy4aDlxZLI5FNh8FqzrG10voc5AGy7RegjLdNkkJa40ugu0I5jA==
> 
> react-navigation-material-bottom-tabs@^2.3.0:
>   version "2.3.4"
>   resolved "https://registry.yarnpkg.com/react-navigation-material-bottom-tabs/-/react-navigation-material-bottom-tabs-2.3.4.tgz#fddcd1c3de9355e6c527a612b23dfb4319f6380b"
>   integrity sha512-NHHFsDg8AJupfPJ2ybIjCzT8VifBFd0LXxAO+RBermtHF2wrHVyFIcpTnYDr1WHgwwRAOrKKg1Hd2TG7TjX6Bg==
> 
> react-navigation-stack@^1.7.3:
>   version "1.10.3"
>   resolved "https://registry.yarnpkg.com/react-navigation-stack/-/react-navigation-stack-1.10.3.tgz#e714e442b20427f0d2d3c18fce1f9e8cfe69be0b"
>   integrity sha512-1gksFi/g/Lg9sBhgLlD0OiEB5xnatHb4C0eNMA5tli9cTVlhq375XNPIqOiTyftibBmjdApAsZFj5srUCoOu/w==
>   dependencies:
>     prop-types "^15.7.2"
> 
> react-navigation-tabs@^2.7.0:
>   version "2.11.0"
>   resolved "https://registry.yarnpkg.com/react-navigation-tabs/-/react-navigation-tabs-2.11.0.tgz#fbea5c8154b6b1b86e1117a1184b98069c5b8bfa"
>   integrity sha512-mrnHfTVKVvoy5AWJY3vLt6cQLZQlVLgGUykTZerFBdTmxC/rFdsv+y2ec+rmSNy7u5nX+hlQBFvm/MIJ7w01wQ==
>   dependencies:
>     hoist-non-react-statics "^3.3.2"
>     react-lifecycles-compat "^3.0.4"
>     react-native-iphone-x-helper "^1.3.0"
>     react-native-tab-view "^2.15.2"
> 
> react-navigation@^4.1.1:
>   version "4.4.4"
>   resolved "https://registry.yarnpkg.com/react-navigation/-/react-navigation-4.4.4.tgz#8cda2219196311db440e54998bc724523359949f"
>   integrity sha512-08Nzy1aKEd73496CsuzN49vLFmxPKYF5WpKGgGvkQ10clB79IRM2BtAfVl6NgPKuUM8FXq1wCsrjo/c5ftl5og==
>   dependencies:
>     "@react-navigation/core" "^3.7.9"
>     "@react-navigation/native" "^3.8.4"
> ```
> 
> I'm on Ubuntu 18.04.
> Let me know what other information I can provide to help.

It is because vue-native runs on react native. 
since this isnt my thread, i realized the owner deleted my update branch about that issue.
I advise you to vistit youtube.com/crankluga , i have tutorials on vue native created recently where i solve many issues among which is yours.
