### ISSUE TITLE
TabNavigation Icon

### ISSUE THREAD

**Issue by cargie** [GeekyAnts/vue-native-router#5]
I am trying to replace the label with Icon but when I use

`navigationOptions: ({ navigation }) => ({`
`            tabBarIcon: ({ focused, tintColor }) => {`
`                const { routeName } = navigation.state;`
`                return <ionicons name="people">`
`            },`
` }),`

It will generate an error which looks for React.

**Comment by neeraj-singh47** [comment]
@cargie Refer to issue https://github.com/GeekyAnts/vue-native-core/issues/62. You'll have to import React in your file which is already installed
