### ISSUE TITLE
Back arrow does not appear automatically when using react navigation

### ISSUE THREAD

**Issue by EddyTheDove** [GeekyAnts/vue-native-router#6]
When navigating between screens from the Drawer using react navigation, back arrow does not appear automatically.

**Comment by neeraj-singh47** [comment]
@EddyTheDove Can you explain a little more about the issue?

**Comment by EddyTheDove** [comment]
I am on screen A, I navigate to screen B by clicking on a menu item in Drawer.
 
Expectation: Screen B navigation should display the back arrow
Actual: Screen B navigation does not display the back arrow

**Comment by neeraj-singh47** [comment]
@EddyTheDove You are not navigating from screen A to screen B directly from screen A right? You navigate to screen B through a drawer like sidebar?

**Comment by EddyTheDove** [comment]
Yes, I do navigate through a drawer. I expect the app to behave exactly like Google Maps. On Google Maps, if you open a link from the drawer, you have the back button.

**Comment by neeraj-singh47** [comment]
@EddyTheDove You'll have to manually add those buttons. The buttons are displayed by default

**Comment by EddyTheDove** [comment]
ok Thank you.
