### ISSUE TITLE
how to adaptor IphoneXR

### ISSUE THREAD

**Issue by lenvonsam** [GeekyAnts/vue-native-router#9]
tabNavigation icon only adaptor iphoneX but not adaptor iphoneXR
how to fix this bug?
iphoneXR screenshot
![image](https://user-images.githubusercontent.com/10168476/51581060-982c9e00-1f01-11e9-863a-43d450c08440.png)
iphoneX screenshot
![image](https://user-images.githubusercontent.com/10168476/51581118-c6aa7900-1f01-11e9-80a5-d4c8cabcdcd7.png)

**Comment by RishabhKarnad** [comment]
@lenvonsam You should not face this issue with the latest `vue-native-router`. Please feel free to reopen if this issue persists.
